package skywaysolutions.app.gui;

import skywaysolutions.app.gui.control.StatusBar;
import skywaysolutions.app.staff.StaffRole;
import skywaysolutions.app.utils.AccessorManager;
import skywaysolutions.app.utils.CheckedException;
import skywaysolutions.app.utils.Decimal;
import skywaysolutions.app.utils.PersonalInformation;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 * This class provides a way to create and edit blank types.
 *
 * @author Alfred Manville
 */
public class BlankTypeEditor extends JDialogx {
    private JSpinner spinnerTypeCode;
    private JPanel panelTypeCode;
    private JTextArea textAreaDescription;
    private JButton buttonCancel;
    private StatusBar statusBar;
    private JPanel Root;
    private JButton buttonOk;
    private final JTextField textFieldRTypeCode;
    private final AccessorManager manager;
    private Integer id;

    /**
     * Constructs a new instance of AccountEditor with the specified owner, if reusable and the accessor manager instance.
     *
     * @param owner    The window owner or null.
     * @param reusable If this dialog is reusable.
     * @param manager  The accessor manager instance.
     */
    public BlankTypeEditor(Window owner, boolean reusable, AccessorManager manager) {
        super(owner, "", reusable);
        this.manager = manager;
        //Setup readonly textfields (Used as readonly controls that swap with controls that have to be disabled to be readonly)
        textFieldRTypeCode = new JTextField();
        textFieldRTypeCode.setEditable(false);
        //Setup form contents
        setContentPane(Root);
        //getRootPane().setDefaultButton(buttonOk);
        //Setup form closing events
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                hideDialog();
            }
        });
        //Setup controls and their events
        spinnerTypeCode.setModel(new SpinnerNumberModel(100, 100, 999, 1));
        buttonCancel.addActionListener(e -> {
            if (!statusBar.isInHelpMode()) hideDialog();
        });
        buttonOk.addActionListener(e -> {
            if (!statusBar.isInHelpMode()) {
                try {
                    //Create or update blank type information
                    if (id == null)
                        manager.stockAccessor.createBlankType(((Number) spinnerTypeCode.getValue()).intValue(), textAreaDescription.getText());
                    else
                        manager.stockAccessor.setBlankTypeDescription(id, textAreaDescription.getText());
                    hideDialog();
                } catch (CheckedException ex) {
                    statusBar.setStatus(ex, 2500);
                }
            }
        });
        //Finalize form
        pack();
        setMinimumSize(Root.getMinimumSize());
        dsize = getSize();
        statusBar.createPrompt(this);
    }

    private void updateInterfaceState() throws CheckedException {
        //Readonly blank type Code if not editable
        swapControl(panelTypeCode, spinnerTypeCode, textFieldRTypeCode, (id == null) ? spinnerTypeCode : textFieldRTypeCode);
    }

    /**
     * Sets the blank type ID being edited or null for creation.
     *
     * @param id The blank type ID or null.
     * @throws CheckedException A refresh error occurred.
     */
    public void setBlankTypeID(Integer id) throws CheckedException {
        this.id = id;
        if (id != null) manager.stockAccessor.refreshBlankType(id);
    }

    @Override
    public void showDialog() {
        if (reusable || !shown) {
            try {
                setTitle((id == null) ? "Blank Type Creator" : "Blank Type Editor");
                if (id == null) {
                    spinnerTypeCode.setValue(100);
                    textAreaDescription.setText("");
                } else {
                    spinnerTypeCode.setValue(id);
                    textFieldRTypeCode.setText(String.valueOf(id));
                    textAreaDescription.setText(manager.stockAccessor.getBlankTypeDescription(id));
                }
                updateInterfaceState();
            } catch (CheckedException e) {
                statusBar.setStatus(e, 2500);
            }
        }
        super.showDialog();
    }

    @Override
    public void hideDialog() {
        statusBar.deactivateHelp();
        super.hideDialog();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Root = new JPanel();
        Root.setLayout(new GridBagLayout());
        Root.setPreferredSize(new Dimension(360, 200));
        final JLabel label1 = new JLabel();
        label1.setMaximumSize(new Dimension(88, 16));
        label1.setMinimumSize(new Dimension(88, 16));
        label1.setPreferredSize(new Dimension(88, 16));
        label1.setText("Type Code:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 0.25;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 2, 0, 0);
        Root.add(label1, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(176, 37));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 0.75;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 2, 0, 2);
        Root.add(panel1, gbc);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-4473925)), "Type Description:", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        scrollPane1.setVerticalScrollBarPolicy(22);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane1, gbc);
        textAreaDescription = new JTextArea();
        textAreaDescription.setLineWrap(true);
        textAreaDescription.setPreferredSize(new Dimension(200, 14));
        textAreaDescription.setWrapStyleWord(true);
        scrollPane1.setViewportView(textAreaDescription);
        panelTypeCode = new JPanel();
        panelTypeCode.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        Root.add(panelTypeCode, gbc);
        spinnerTypeCode = new JSpinner();
        spinnerTypeCode.setPreferredSize(new Dimension(88, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelTypeCode.add(spinnerTypeCode, gbc);
        buttonCancel = new JButton();
        buttonCancel.setAlignmentX(0.5f);
        buttonCancel.setMaximumSize(new Dimension(88, 30));
        buttonCancel.setMinimumSize(new Dimension(88, 30));
        buttonCancel.setPreferredSize(new Dimension(88, 30));
        buttonCancel.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Root.add(buttonCancel, gbc);
        statusBar = new StatusBar();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        Root.add(statusBar.$$$getRootComponent$$$(), gbc);
        buttonOk = new JButton();
        buttonOk.setAlignmentX(0.5f);
        buttonOk.setMaximumSize(new Dimension(88, 30));
        buttonOk.setMinimumSize(new Dimension(88, 30));
        buttonOk.setPreferredSize(new Dimension(88, 30));
        buttonOk.setText("Ok");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Root.add(buttonOk, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Root;
    }
}
