package skywaysolutions.app.gui;

import skywaysolutions.app.gui.control.DateField;
import skywaysolutions.app.gui.control.StatusBar;
import skywaysolutions.app.gui.control.VTextField;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class Transacter {
    private JComboBox comboBoxCurrency;
    private VTextField textFieldAmount;
    private JLabel labelAmount;
    private JComboBox comboBoxPayment;
    private JPanel panelAux;
    private JTextField textFieldPaidAmount;
    private JButton buttonRefund;
    private JButton buttonCancel;
    private JButton buttonOk;
    private StatusBar statusBar;
    private JPanel panelCurrency;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Transaction date:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 0.1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 2, 0, 0);
        panel1.add(label1, gbc);
        final DateField nestedForm1 = new DateField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 0.1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(nestedForm1.$$$getRootComponent$$$(), gbc);
        final JLabel label2 = new JLabel();
        label2.setPreferredSize(new Dimension(86, 16));
        label2.setText("Payment Currency:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.weighty = 0.1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 2, 0, 0);
        panel1.add(label2, gbc);
        textFieldAmount = new VTextField();
        textFieldAmount.setAlignmentX(0.5f);
        Font textFieldAmountFont = this.$$$getFont$$$(null, -1, -1, textFieldAmount.getFont());
        if (textFieldAmountFont != null) textFieldAmount.setFont(textFieldAmountFont);
        textFieldAmount.setMinimumSize(new Dimension(65, 30));
        textFieldAmount.setPreferredSize(new Dimension(65, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 0.5;
        gbc.weighty = 0.1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 2);
        panel1.add(textFieldAmount, gbc);
        labelAmount = new JLabel();
        labelAmount.setAlignmentX(0.5f);
        Font labelAmountFont = this.$$$getFont$$$(null, -1, -1, labelAmount.getFont());
        if (labelAmountFont != null) labelAmount.setFont(labelAmountFont);
        labelAmount.setMaximumSize(new Dimension(65, 16));
        labelAmount.setMinimumSize(new Dimension(65, 16));
        labelAmount.setOpaque(false);
        labelAmount.setPreferredSize(new Dimension(65, 16));
        labelAmount.setText("Amount:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 0.5;
        gbc.weighty = 0.1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 2, 0, 0);
        panel1.add(labelAmount, gbc);
        final JLabel label3 = new JLabel();
        label3.setPreferredSize(new Dimension(86, 16));
        label3.setText("Payment Type:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 0.5;
        gbc.weighty = 0.1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 2, 0, 0);
        panel1.add(label3, gbc);
        comboBoxPayment = new JComboBox();
        comboBoxPayment.setEditable(false);
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Cash");
        defaultComboBoxModel1.addElement("Card");
        defaultComboBoxModel1.addElement("Invoice");
        defaultComboBoxModel1.addElement("Cheque");
        comboBoxPayment.setModel(defaultComboBoxModel1);
        comboBoxPayment.setPreferredSize(new Dimension(86, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 0.5;
        gbc.weighty = 0.1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(comboBoxPayment, gbc);
        panelAux = new JPanel();
        panelAux.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 0.1;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panelAux, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-4473925)), "Paid amount and Refund:", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        textFieldPaidAmount = new JTextField();
        textFieldPaidAmount.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(textFieldPaidAmount, gbc);
        buttonRefund = new JButton();
        buttonRefund.setText("Refund");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonRefund, gbc);
        buttonCancel = new JButton();
        buttonCancel.setAlignmentX(0.5f);
        buttonCancel.setMaximumSize(new Dimension(65, 30));
        buttonCancel.setMinimumSize(new Dimension(65, 30));
        buttonCancel.setPreferredSize(new Dimension(65, 30));
        buttonCancel.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonCancel, gbc);
        buttonOk = new JButton();
        buttonOk.setAlignmentX(0.5f);
        buttonOk.setMaximumSize(new Dimension(65, 30));
        buttonOk.setMinimumSize(new Dimension(65, 30));
        buttonOk.setPreferredSize(new Dimension(65, 30));
        buttonOk.setText("Ok");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonOk, gbc);
        statusBar = new StatusBar();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(statusBar.$$$getRootComponent$$$(), gbc);
        panelCurrency = new JPanel();
        panelCurrency.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panelCurrency, gbc);
        comboBoxCurrency = new JComboBox();
        comboBoxCurrency.setEditable(true);
        comboBoxCurrency.setPreferredSize(new Dimension(86, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelCurrency.add(comboBoxCurrency, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }
}
