package skywaysolutions.app.gui.tab;

import javax.swing.*;
import java.awt.*;

public class SaleTab {
    private JTable tableListed;
    private JButton buttonAdd;
    private JButton buttonEdit;
    private JButton buttonRefund;
    private JButton buttonRefresh;
    private JPanel Root;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Root = new JPanel();
        Root.setLayout(new GridBagLayout());
        buttonAdd = new JButton();
        buttonAdd.setPreferredSize(new Dimension(30, 30));
        buttonAdd.setText("Add");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.25;
        gbc.weighty = 0.15;
        gbc.fill = GridBagConstraints.BOTH;
        Root.add(buttonAdd, gbc);
        buttonEdit = new JButton();
        buttonEdit.setPreferredSize(new Dimension(30, 30));
        buttonEdit.setText("Edit");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.25;
        gbc.weighty = 0.15;
        gbc.fill = GridBagConstraints.BOTH;
        Root.add(buttonEdit, gbc);
        buttonRefund = new JButton();
        buttonRefund.setPreferredSize(new Dimension(30, 30));
        buttonRefund.setText("Refund");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 0.25;
        gbc.weighty = 0.15;
        gbc.fill = GridBagConstraints.BOTH;
        Root.add(buttonRefund, gbc);
        buttonRefresh = new JButton();
        buttonRefresh.setPreferredSize(new Dimension(30, 30));
        buttonRefresh.setText("Refresh");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 0.25;
        gbc.weighty = 0.15;
        gbc.fill = GridBagConstraints.BOTH;
        Root.add(buttonRefresh, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        scrollPane1.setVerticalScrollBarPolicy(22);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 0.85;
        gbc.fill = GridBagConstraints.BOTH;
        Root.add(scrollPane1, gbc);
        tableListed = new JTable();
        tableListed.setFillsViewportHeight(true);
        tableListed.setPreferredScrollableViewportSize(new Dimension(200, 150));
        scrollPane1.setViewportView(tableListed);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Root;
    }
}
